print('\n'*3)
print('='*50)
n1 = float(input('Digite a primeira nota:'))
n2 = float(input('Digite a segunda nota: '))
m = float((n1+n2)/2)
print('A média foi de {:.2f}'.format(m))
print('='*50)
print('\n'*3)