print('\n'*3)
print('='*50)

n = int(input('Digite um valor:'))
print('')

#primeira tentativa: print('1x{} = {}\n2x{} = {}\n3x{} = {}\n4x{} = {}\n5x{} = {}\n6x{} = {}\n7x{} = {}\n8x{} = {}\n9x{} = {}\n10x{} = {}'.format(n,n*1,n,n*2,n,n*3,n,n*4,n,n*5,n,n*6,n,n*7,n,n*8,n,n*9,n,n*10,))
print('1 x {:2} = {:>2}'.format(n,(n*1)))
print('2 x {:2} = {:>2}'.format(n,(n*2)))
print('3 x {:2} = {:>2}'.format(n,(n*3)))
print('4 x {:2} = {:>2}'.format(n,(n*4)))
print('5 x {:2} = {:>2}'.format(n,(n*5)))
print('6 x {:2} = {:>2}'.format(n,(n*6)))
print('7 x {:2} = {:>2}'.format(n,(n*7)))
print('8 x {:2} = {:>2}'.format(n,(n*8)))
print('9 x {:2} = {:>2}'.format(n,(n*9)))
print('10 x {:2} = {:>2}'.format(n,(n*10)))
print('='*50)
print('\n'*3)