print ('='*20)
nome = input('Qual é seu nome? ')
print ('Prazer em te conhecer {:20}!'.format(nome))
print ('Prazer em te conhecer {:>20}!'.format(nome))
print ('Prazer em te conhecer {:<20}!'.format(nome))
print ('Prazer em te conhecer {:^20}!'.format(nome))
('Prazer em te conhecer {:=^20}!'.format(nome))
print ('='*20)